using Godot;
using System;
using System.Collections.Generic;
using System.Linq;
using CraigStars;
using static CraigStars.Utils.Utils;

namespace CraigStars.UniverseGeneration
{
    /// <summary>
    /// Create fleets for each player based on their race settings and designs
    /// Note: This step will create all fleets in the Player's Designs, which are
    /// generated by the PlayerShipDesignsGenerationStep
    /// </summary>
    public class PlayerFleetGenerationStep : UniverseGenerationStep
    {
        public PlayerFleetGenerationStep(IProvider<Game> gameProvider) : base(gameProvider, UniverseGenerationState.Fleets) { }

        public override void Process()
        {
            Game.Players.ForEach(player =>
            {
                Game.Fleets.AddRange(GenerateFleets(player, player.Homeworld));
            });
        }

        internal List<Fleet> GenerateFleets(Player player, Planet homeworld)
        {
            var fleets = new List<Fleet>();
            var id = 1;
            foreach (var design in player.Designs.Where(d => !d.Hull.Starbase))
            {
                fleets.Add(CreateFleet(design, player, id++, homeworld));
            }
            switch (player.Race.PRT)
            {
                // HE gets 2 extra mini colonizers
                case PRT.HE:
                    fleets.Add(CreateFleet(player.GetLatestDesign(ShipDesignPurpose.Colonizer), player, id++, homeworld));
                    fleets.Add(CreateFleet(player.GetLatestDesign(ShipDesignPurpose.Colonizer), player, id++, homeworld));
                    break;
                // races with second planets get a scout
                case PRT.PP:
                case PRT.IT:
                    if (player.Planets.Count > 1)
                    {
                        // add a scout to the second world
                        fleets.Add(CreateFleet(player.GetLatestDesign(ShipDesignPurpose.Scout), player, id++, player.Planets[1]));
                    }
                    break;
            }

            return fleets;
        }

        internal Fleet CreateFleet(ShipDesign playerDesign, Player player, int id, Planet planet)
        {
            var design = Game.DesignsByGuid[playerDesign.Guid];
            var fleet = new Fleet()
            {
                Id = id
            };
            fleet.BaseName = $"{playerDesign.Name}";
            fleet.Name = $"{fleet.BaseName} #{fleet.Id}";
            fleet.BattlePlan = player.BattlePlans[0];
            player.Stats.NumFleetsBuilt++;
            fleet.Tokens.Add(
                    new ShipToken()
                    {
                        Design = design,
                        Quantity = 1
                    }
                );
            fleet.Position = planet.Position;
            fleet.Orbiting = planet;
            fleet.Waypoints.Add(Waypoint.TargetWaypoint(fleet.Orbiting));
            planet.OrbitingFleets.Add(fleet);
            fleet.PlayerNum = player.Num;

            // aggregate all the design data
            fleet.ComputeAggregate(player);
            fleet.Fuel = fleet.Aggregate.FuelCapacity;

            return fleet;
        }
    }
}